### PR TITLE
Use prettier and husky for code formatting

### PR DESCRIPTION
**Pull request by CameronDiver**
Add prettier to be ran on precommit, with predefined configuration. Runs
on src and typings directory.

Also fixed compiling of typings with newest TS.

Change-type: minor
Signed-off-by: Cameron Diver <cameron@resin.io>

### CODE REVIEW

**Review by flesler — COMMENTED** [review]
A couple of subjective opinions:

1. I would add an `npm script` called sth like `format` and then would set `precommit` to `npn run format`. This way you can run it ad-hoc without using the hook name and you can also alter the hook more cleanly
2. I would have a commit just for the package.json stuff and then another where you reformat the code
3. ~~Can't you have a configuration file for prettier instead of sticking the options in the package.json?~~ ([guess not](https://github.com/prettier/prettier/issues/98), pretty dumb if you ask me)
4. Some have complained about using `precommit` as opposed to `prepush`, because the former runs very often sometimes. I personally don't mind it, and in this case is only linting so I don't know, just bringing it up

**Comment by CameronDiver** [comment]
@flesler 
1. Fair point, I like it :)
2. Yeah maybe that would have been better, but if I'd added it to the `precommit` and then committed, it would have changed the code anyway. I'm not overly bothered for this repo, but next time :+1: 
3. Yup
4. This is fairly quick tbh, less than a second. Plus I'm the only person to have ever done a commit :p but perhaps it's worth looking into, I think I'm going to leave it as-is for now.

**Comment by flesler** [comment]
@CameronDiver you can skip by using `git commit .... --no-verify` FYI. No need to act on this

**Comment by CameronDiver** [comment]
Huh, TIL, thanks man.

**Review by flesler — APPROVED** [review]

**Pull request merged**
